# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "pata_jmicron" "firewire_ohci" "usb_storage" "usbhid" "floppy" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/" = {
        device = "/dev/disk/by-uuid/5b9389c1-23c2-4080-9e68-20de45cad359";
        fsType = "ext4";
    };

#    "/mnt/media1" = {
#        device = "/dev/disk/by-uuid/7E9C49AC9C49602F";
#        fsType = "ntfs";
#    };
#
#    "/mnt/media2" = {
#        device = "/dev/disk/by-uuid/4A04BFFA04BFE6DB";
#        fsType = "ntfs";
#    };
#
#    "/mnt/media3" = {
#        device = "/dev/disk/by-uuid/8EB86AE8B86ACE71";
#        fsType = "ntfs";
#    };
  };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 2;
  powerManagement.cpuFreqGovernor = "ondemand";
}
