# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "firewire_ohci" "usbhid" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/" = {
        device = "/dev/disk/by-uuid/ce598fb8-87c9-4c3f-a494-59e2c9a5c511";
        fsType = "ext4";
    };

    "/mnt/storage" = {
        device = "/dev/disk/by-uuid/054367f5-9362-4bbd-b9c1-25e5609997ac";
        fsType = "ext4";
    };
  };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
}
